version: '3.9'

services:
  db:
    image: postgres:16
    container_name: muras-backend-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: social
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d social"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: muras-backend:latest
    container_name: muras-backend
    environment:
      PORT: "8080"
      ALLOW_CORS: "true"
      DATABASE_URL: "postgres://postgres:postgres@db:5432/social?sslmode=disable"
      JWT_SECRET: "change-me-in-prod"
      DEFAULT_ADMIN_EMAIL: "admin@example.com"
      DEFAULT_ADMIN_PASSWORD: "admin123"
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  pgdata: